### ISSUE TITLE
Diagramar macroprocesso de pedido

### ISSUE THREAD

**Issue by victorapa** [victorapa/dlvry#3]
Diagramar processo de pedido contendo todos os microprocessos, sendo eles:
- [x] Gerar pedido (Consumidor)
- [x] Escolher meio de pagamento (Consumidor) 
- [x] Confirmação do pedido (Estabelecimento)
- [x] Confirmação do pagamento (Estabelecimento)
- [x] Despache do produto (Estabelecimento)
- [x] Confirmação do despache do produto (Transportador)
- [x] Confirmação da entrega (Transportador)

**Comment by rafaelbotazini** [comment]
Algum documento?

**Comment by Andre0x1** [comment]
[Processo_de_Negocios-Pedido_TIS_II_Dlvry.zip](https://github.com/victorapa/dlvry/files/2999372/Processo_de_Negocios-Pedido_TIS_II_Dlvry.zip)

**Comment by Andre0x1** [comment]
![Processo_de_Negocios-Pedido_TIS_II_Dlvry](https://user-images.githubusercontent.com/48383967/54866680-eae5d300-4d55-11e9-9547-a5fe1d35a2e7.png)

**Comment by rafaelbotazini** [comment]
Processo corrigido:

![processamento-pedido](https://user-images.githubusercontent.com/18739282/55843061-9fc90f80-5b0c-11e9-869e-c2a3259a16ff.png)

Novas regras:

* O estabelecimento pode rejeitar um pedido
* O cliente e o estabelecimento devem confirmar a entrega do produto
