### ISSUE TITLE
Basic Class Diagram

### ISSUE THREAD

**Issue by LucasHaddad** [victorapa/dlvry#7]
[draw.io](https://drive.google.com/open?id=1kdCHBb-sbq4nDfYF7mZvaX0j4d-vddZ6)

**Comment by rafaelbotazini** [comment]
Please, update the diagram in order to fulfill the request on the proposed model, at issue #8 .

Thanks in advance.

**Comment by LucasHaddad** [comment]
O que seriam materiais usados? Faremos controle da manufatura?

**Comment by LucasHaddad** [comment]
Ou, valida esqueci, esqueci de falar que atualizei.

**Comment by rafaelbotazini** [comment]
O que é o taxa representa na classe Pedido?
