### ISSUE TITLE
Modelo de processo de negócio - Entrega 2

### ISSUE THREAD

**Issue by rafaelbotazini** [victorapa/dlvry#8]
Segundo o [modelo proposto](https://docs.google.com/document/d/1PsueI_b4KZQctRr-qaDazdjyZpE75BApVaGszo35ZW4/edit?usp=sharing):

> ...as informações necessárias para gerar os indicadores devem estar contempladas no diagrama de classe

[Link para o documento entregue na sprint 2](https://docs.google.com/document/d/1ysMKyTdDOzS1Wvj8yI8VHXk1-Me1eLzRGetdwkHolcU/edit?usp=sharing)

**Comment by victorapa** [comment]
Abre um pull-request pra subir esse documento.
